### PR TITLE
install cantera during travis build

### PR DESCRIPTION
**Pull request by nickvandewiele**
is a first step in using cantera simulations to validate generated models by comparing model observables (eg speciation data, ignition delays, etc...-) rather than model details, which is the current state.

cantera is installed via bryan weber's anaconda channel. Currently installs v2.2.1

[Here](https://github.com/Cantera/cantera/issues/261#issuecomment-167114919) it is discussed how cantera can be installed via anaconda.

### CODE REVIEW

**Comment by whgreen** [comment]
Nick,
  Please beware that Cantera and CHEMKIN don't interpret CHEMKIN files exactly the same way.
   Bill

Sent from my iPhone

On Feb 13, 2016, at 5:53 PM, NICK VANDEWIELE <notifications@github.com<mailto:notifications@github.com>> wrote:


is a first step in using cantera simulations to validate generated models by comparing model observables (eg speciation data, ignition delays, etc...-) rather than model details, which is the current state.

cantera is installed via bryan weber's anaconda channel. Currently installs v2.2.1

Here<https://github.com/Cantera/cantera/issues/261#issuecomment-167114919> it is discussed how cantera can be installed via anaconda.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ReactionMechanismGenerator/RMG-tests/pull/5

Commit Summary

  *   install cantera via bryan weber's anaconda channel

File Changes

  *   M install.sh<https://github.com/ReactionMechanismGenerator/RMG-tests/pull/5/files#diff-0> (5)

Patch Links:

  *   https://github.com/ReactionMechanismGenerator/RMG-tests/pull/5.patch
  *   https://github.com/ReactionMechanismGenerator/RMG-tests/pull/5.diff

**Comment by nyee** [comment]
I haven't not actually looked into it yet. But just for record keeping and clarification, Bill is referencing potential differences in the handling of duplicate reactions and pdep reactions (plog and chebyshev format).

**Comment by bryanwweber** [comment]
I would also note that I haven't tested the recipes on very many different systems (and especially on systems with different versions of the compilers than I used) so any feedback on errors or such would be greatly appreciated. You can post on the issue at Cantera or you can email me directly bryan.w.weber@gmail.com Thanks!

**Comment by speth** [comment]
The Chebyshev implementations are consistent between Cantera and Chemkin, at least in the T and P range where the polynomial is defined. I do recall there being discrepancies when you go outside that region, though.

For P-log, Cantera doesn't implement the special case that's described in the Chemkin manual of using just the given rate constant if you're within some distance of one of the reference pressures (1%) because I thought it sounded like a recipe for impossible-to-debug numerical troubles due to the corresponding discontinuities. I also think that in the case of reactions parameterized by multiple rates at each pressure, this is transcribed incorrectly in many published mechanisms as two separate reactions where it should actually be written as a single reaction with multiple "PLOG" lines for each pressure. As far as I can tell, both Cantera and Chemkin handle reactions written this way in the same manner, though.

Other than that, I think the Cantera parser is in general more strict about a number of things than the Chemkin parser. The only thing that I know the Chemkin parser checks that Cantera doesn't is for reactions which are declared duplicate but have no actual duplicate reaction. If there's anything that Cantera's not checking for that it should, feel free to create an issue on the Cantera repository.

**Comment by nyee** [comment]
Thank you for the clarifications, Ray. It sounds like most of those things are improvements over Chemkin's parsers. 

The only thing I'd like to further check is the user input error of using duplicate PLOG reactions vs all rates in one PLOG. Enoch does a good job of documenting the issue here:   #https://github.com/ReactionMechanismGenerator/RMG-Py/issues/147. For our tests, we take an RMG-generated model and will convert it with Cantera's chemkin2cti.py. 

@connie Does RMG write out these PLOGS correctly in its chemkin files? What if a kinetics library is inputted where we have the incorrect format (Case 2). Would RMG automatically fix that?

Also, do we want to check PLOGS somewhere else? I'm started to think that this test we are writing for testing RMG consistency may actually be quite useful for users of RMG trying to create models. In that case, the input may not always be a RMG-generated model.

@nickvandewiele Back to the original topic, I'm 80% sure I locally installed from the stable build with the command:

git clone https://github.com/bryanwweber/conda-recipes.git
cd conda-recipes
conda build --python=2.7  cantera-stable

Judging from the comments, I think what you wrote will point to the same version, but maybe we should figure out a way to test this.

**Pull request merged**
