### PR TITLE
Added a catalytic combustion example

### PR DESCRIPTION
**Pull request by kblondal**
Should take around 3 minutes to run.

### CODE REVIEW

**Review by rwest — COMMENTED** [review]
In order to test the linear scaling relationships, we could use binding energies  other than platinum.

It might run faster with generate output html  off

**Comment by kblondal** [comment]
Sounds good. Do you propose binding energies for a specific metal? Otherwise I can look up binding energies on for example Pd(111) and put those instead.

**Comment by mliu49** [comment]
Thanks! I agree that you can probably turn generate output html off.

Could you also add the test to travis.yml so it gets run? It can probably go in the same section as the minimal example: https://github.com/ReactionMechanismGenerator/RMG-tests/blob/master/.travis.yml#L33

Once this is ready, we can make a dummy RMG-Py branch to make travis run the new test.

**Comment by mliu49** [comment]
Seems like this might be more complicated than expected. The test failed because there isn't a chem_annotated.inp file: https://travis-ci.org/ReactionMechanismGenerator/RMG-tests/jobs/544305349

So we'll have to update RMG-tests to account for that. What are the output files that we should compare for catalyst jobs?

**Comment by rwest** [comment]
`chem_annotated-gas.inp` and `chem_annotated-surface.inp` would be the equivalent. (Or the cantera will merge them into a single `.cti` file)

**Comment by sevyharris** [comment]
I'm making a [new PR](https://github.com/ReactionMechanismGenerator/RMG-tests/pull/85)to avoid the difficulties of switching the commits over from master to main.

**Comment by sevyharris** [comment]
closing this, since it's been moved here: https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2514

**Pull request closed without merging**
